### ISSUE TITLE
issue with package

### ISSUE THREAD

**Issue by archeloss** [marvinody/mercari#10]
the package currently displays this error when attempting to install through pip:

```
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\1\AppData\Local\Temp\pip-install-u51u4dpk\mercari_8d9ad5b0a04246f4ad2e303b332f388c\setup.py", line 7, in <module>
          long_description = fh.read()
        File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 160: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

are you planning on updating the package at all? if not, is there anyway we can fix this issue individually?

**Comment by marvinody** [comment]
I was not able to replicate with python version 3.9.10

Can you share what version of python and pip you're trying to use this package with?

**Comment by Shaddox** [comment]
Hello,

I can confirm, I'm experiencing the same error. 
I'm using Python 3.9.10 , pip 22.1.2 on Windows 10 in a venv. 

Any ideas?

**Comment by marvinody** [comment]
Using the same versions on Unix I was not able to replicate. A friend tried and was able to reproduce. I've pushed a fix and deployed it. Try installing the latest version with 

```pip install mercari==1.0.2```

I believe the issue was an encoding thing on Windows. Please let me know if the version bump solves the problem so I can close this or share if the same or different issue.

**Comment by Shaddox** [comment]
@marvinody I just installed it successfully. Thank you very much for your time and effort!
