### ISSUE TITLE
I want to use generate_DPOP to login to Mercari JP.

### ISSUE THREAD

**Issue by Haruqun** [marvinody/mercari#14]
Hello.
I have seen your wonderful script.

I am creating an easy purchase script for Mercari in PHP.
The system is currently about 50% complete.
The purpose is to be able to instantly make a purchase by clicking [the buy button] from the list of products retrieved.
I am currently having a problem, it is not possible to login to Mercari from the PHP script.
(I was able to generate an access token, but could not log in due to an incorrect DPOP.)

Now, I think your generate_DPOP is a very nice library.
I want to use generate_DPOP in a script I am creating to implement a function to log in to mercari.ljp.
Have you ever created a login process in api.mercari.jp using this generate_DPOP?

I can find very little information about api.mercari.jp in Japan and abroad.
You are the only knowledgeable person I could find.
Please, could you give me some support?

Best regards.

**Comment by marvinody** [comment]
I am not associated with Mercari and the code on this repo was made by looking at their frontend public JavaScript code, and working backwards. **I have never tried to login with this method and am unsure of the specifics.**

I tried to leave comments in the DPOP generation file to have it make sense when reading for other people.

The rough steps you need to accomplish in PHP are
- generate ECC keys (private and public)
- format the data (url, uuid, and etc in correct format)
- figure out how to sign data with the private key

My PHP knowledge ended a long a time ago, so I'm not sure how easy it would be to reproduce this code in that language.
